export const REALM_CANON = [
  {
    step: 1,
    id: "HUNGRY_GHOST",
    label: "Hungry Ghost",
    color: "Black",
    hex: "#1a1a1a",
    era: "Palaeolithic",
    state: "Instinct & Survival",
  },
  {
    step: 2,
    id: "HELL",
    label: "Hell",
    color: "Purple",
    hex: "#6f42c1",
    era: "Neolithic",
    state: "Painful experiences",
  },
  {
    step: 3,
    id: "ANIMALS",
    label: "Animals",
    color: "Gold",
    hex: "#d4af37",
    era: "Metal Age",
    state: "Impulse & Routine",
  },
  {
    step: 4,
    id: "HUMANS",
    label: "Humans",
    color: "Blue",
    hex: "#2563eb",
    era: "Antiquity",
    state: "Self-awareness",
  },
  {
    step: 5,
    id: "TITANS",
    label: "Titans",
    color: "Red",
    hex: "#dc2626",
    era: "Renaissance",
    state: "Conflict & Ambition",
  },
  {
    step: 6,
    id: "SEMIGODS",
    label: "SemiGods",
    color: "White",
    hex: "#f3f4f6",
    era: "Enlightenment",
    state: "Refinement & Power",
  },
  {
    step: 7,
    id: "BUDDHA",
    label: "Buddha",
    color: "Rainbow",
    hex: "#22c55e",
    era: "Curvist Golden Era",
    state: "Liberation",
  },
] as const;